name: compare_BCU_RN Build Release

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
          python-version: '3.10'

    - name: Set up ENV
      run: |
        chcp 65001
        echo ("RELEASE_VERSION=" + $env:GITHUB_REF.replace('refs/tags/', '')) >> $env:GITHUB_ENV
        echo ("RELEASE_TITLE=compare_BCU_RN_" + $env:GITHUB_REF.replace('refs/tags/', '') + "_windows_64bit") >> $env:GITHUB_ENV
        echo ("RELEASE_FILENAME=compare_BCU_RN_" + $env:GITHUB_REF.replace('refs/tags/', '') + "_windows_64bit.zip") >> $env:GITHUB_ENV
        git fetch --tags --force
    - name: Get tag message
      id: tag_data
      uses: ericcornelissen/git-tag-annotation-action@v2
    - name: Test ENV
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        echo $RELEASE_TITLE
        echo ${{ env.RELEASE_TITLE }}
        echo $RELEASE_FILENAME
        echo ${{ env.RELEASE_FILENAME }}
        echo $TAG_MESSAGE
        echo '${{ steps.tag_data.outputs.git-tag-annotation }}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build with PyInstaller for windows
      run: |
        pyinstaller --noconfirm --distpath %cd%\ --name compare_BCU_RN_${{ env.RELEASE_VERSION }}.exe --onefile %cd%\compare_BCU_RN.py
      shell: cmd

    - name: Archive release
      run: 7z a -tzip ${{ env.RELEASE_FILENAME }} compare_BCU_RN_${{ env.RELEASE_VERSION }}.exe

    - name: Create GitHub Release with asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        name: ${{ env.RELEASE_TITLE }}
        body: ${{ steps.tag_data.outputs.git-tag-annotation }}
        draft: false
        prerelease: false
        files: ${{ env.RELEASE_FILENAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}